# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-22.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Copy .next directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/.next'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/.next'

# Copy node_modules directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/node_modules'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/node_modules'

# Copy public directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/public'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# Copy server.js and web.config files
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      server.js
      web.config
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- publish: $(Build.ArtifactStagingDirectory)
  artifact: drop
  displayName: 'Drop Artifacts'