export const ApiKey = 'e-Labex-ApiKey'
export const BusinessUnit = 'e-Labex-BusinessUnit'
export const UserName = 'e-Labex-UserName'
export const FullName = 'e-Labex-FullName'
export const Signature = 'e-Labex-Signature'